In [26]:
X = np.array([[1, 2], [10, 11], [50, 51], [100, 101]])
y = np.array([1, 2, 3, 4])
w=np.array([1, 2])
w0 = 1

In [22]:
import numpy as np

In [23]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00],
       [2.20264658e+04, 5.98741417e+04],
       [5.18470553e+21, 1.40934908e+22],
       [2.68811714e+43, 7.30705998e+43]])

In [28]:
expp = np.exp(-y*(X.dot(w)+w0))

In [34]:
expp/(1+expp)*(-y)

array([-2.47262316e-003, -4.34104402e-029, -1.36758416e-199,
       -0.00000000e+000])

In [36]:
X.T*expp/(1+expp)*(-y)

array([[-2.47262316e-003, -4.34104402e-028, -6.83792079e-198,
        -0.00000000e+000],
       [-4.94524631e-003, -4.77514842e-028, -6.97467920e-198,
        -0.00000000e+000]])

In [37]:
expp/(1+expp)*(-y)*X.T

array([[-2.47262316e-003, -4.34104402e-028, -6.83792079e-198,
        -0.00000000e+000],
       [-4.94524631e-003, -4.77514842e-028, -6.97467920e-198,
        -0.00000000e+000]])

In [40]:
np.mean(expp/(1+expp)*(-y)*X.T, axis=1)

array([-0.00061816, -0.00123631])

In [41]:
expp

array([2.47875218e-003, 2.17052201e-029, 4.55861386e-200, 0.00000000e+000])

In [43]:
(X.dot(w)+w0)*y

array([   6,   66,  459, 1212])

In [48]:
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error

X_data, y_data = make_classification(
            n_samples=10000, n_features=20, 
            n_classes=2, n_informative=20, 
            n_redundant=0,
            random_state=42
        )
algo = LogisticRegression()
np.mean(cross_val_score(algo, X_data, y_data, cv=2, scoring='accuracy'))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


0.7983